const initialTours=[{id:'city',title:'Шанхай: первое свидание',category:'Город',duration:'5–6 часов',image:'garden.jpg',tag:'НАЧНИТЕ С ЭТОГО',description:'От тихих садов старого города до панорамы будущего. Все грани Шанхая за одну прогулку.',route:'Сад Юйюань → улочки старого города → набережная Вайтань → панорама Пудуна',active:true},{id:'night',title:'Когда город зажигает огни',category:'Вечер',duration:'3–4 часа',image:'skyline.jpg',tag:'ОСОБАЯ АТМОСФЕРА',description:'Огни набережной, отражения в Хуанпу и тот самый вид, ради которого хочется задержаться.',route:'Вечерний Вайтань → прогулка вдоль Хуанпу → лучшие точки для фотографий',active:true},{id:'water',title:'На один день — в другой Китай',category:'За городом',duration:'6–7 часов',image:'canal.jpg',tag:'ЗАМЕДЛИТЬСЯ',description:'Чжуцзяцзяо: каналы, каменные мосты и чайные. Маленькое путешествие в большой истории.',route:'Старинные мосты → прогулка вдоль каналов → свободное время и чай',active:true}];
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(k,f){try{const v=JSON.parse(localStorage.getItem(k));return Array.isArray(v)?v:f}catch{return f}}
let tours=read('cl-tours-v1',initialTours),leads=read('cl-leads-v1',[]),filter='Все',adminTab='tours';
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{toast('Не удалось сохранить: проверьте настройки браузера.');return false}}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
function renderTours(){const items=tours.filter(t=>t.active&&(filter==='Все'||t.category===filter));$('#tour-grid').innerHTML=items.length?items.map(t=>`<article class="tour-card"><div class="tour-image"><img src="assets/${esc(t.image)}" alt="${esc(t.title)}" loading="lazy"><span class="tag">${esc(t.tag)}</span></div><div class="tour-meta"><span>${esc(t.category)}</span><span>${esc(t.duration)} · индивидуально</span></div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><div class="tour-bottom"><span>Подробнее о маршруте</span><button class="circle" data-detail="${esc(t.id)}" aria-label="Подробнее: ${esc(t.title)}">↗</button></div></article>`).join(''):'<p class="empty">В этой коллекции пока нет маршрутов. Посмотрите все впечатления.</p>';document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function openModal(html){$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
$('.close').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close()}});
function detail(id){const t=tours.find(t=>t.id===id);if(!t)return;openModal(`<img class="detail-photo" src="assets/${esc(t.image)}" alt="${esc(t.title)}"><div class="eyebrow accent">${esc(t.category)} · ${esc(t.duration)}</div><h2>${esc(t.title)}</h2><p>${esc(t.description)}</p><h3>Идея маршрута</h3><p>${esc(t.route)}</p><p class="note">Демонстрационная программа. Входные билеты, транспорт, доступность мест и итоговая стоимость уточняются при согласовании.</p><button class="button red" id="choose">Хочу на эту экскурсию ↗</button>`);$('#choose').onclick=()=>booking(t.id)}
function booking(id=''){openModal(`<div class="eyebrow accent">ВАШЕ ПУТЕШЕСТВИЕ НАЧИНАЕТСЯ ЗДЕСЬ</div><h2>Какой у вас <em>план?</em></h2><form id="booking" class="form-grid"><label>Как вас зовут<input name="name" required maxlength="80" autocomplete="given-name" placeholder="Ваше имя"></label><label>Telegram или телефон<input name="contact" required maxlength="120" placeholder="@username или +7…"></label><label>Что интересно<select name="tour"><option value="Индивидуальный маршрут">Помогите выбрать</option>${tours.filter(t=>t.active).map(t=>`<option ${id===t.id?'selected':''} value="${esc(t.title)}">${esc(t.title)}</option>`).join('')}</select></label><label>Желаемая дата<input type="date" name="date" min="${[new Date().getFullYear(),String(new Date().getMonth()+1).padStart(2,'0'),String(new Date().getDate()).padStart(2,'0')].join('-')}"></label><label>Пара слов о поездке<textarea name="message" maxlength="1500" placeholder="Сколько вас, что любите, о чём мечтаете…"></textarea></label><p class="note">Это демоформа: заявка сохранится только в вашем браузере и появится в демо-админке. Используйте вымышленные данные. Для реального обращения — <a class="text-link" href="https://t.me/shanghai_russ" target="_blank" rel="noopener">Telegram Katrin ↗</a></p><button class="button red" type="submit">Сохранить тестовую заявку ↗</button></form>`);$('#booking').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.name.trim()||!data.contact.trim())return;const next=[{...data,id:crypto.randomUUID(),status:'Новая',created:new Date().toISOString()},...leads];if(!save('cl-leads-v1',next))return;leads=next;openModal('<div class="eyebrow accent">ГОТОВО</div><h2>Начало положено.</h2><p>Тестовая заявка сохранена в этом браузере. Посмотрите её в разделе «Заявки» демо-админки.</p><a class="button red" id="goto-admin" href="#admin">Открыть админку ↗</a>');$('#goto-admin').onclick=()=>{$('#modal').close();adminTab='leads';renderAdmin()}}}
$('#plan').onclick=()=>booking();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderTours()});
function route(){const admin=location.hash==='#admin';$('#site').hidden=admin;$('#admin').hidden=!admin;if(admin){renderAdmin();window.scrollTo(0,0)}}window.addEventListener('hashchange',route);
function renderAdmin(){$('#admin').innerHTML=`<div class="admin-shell"><div class="admin-head"><div><div class="eyebrow accent">CHINA LUX / УПРАВЛЕНИЕ</div><h2>Добро пожаловать, Katrin.</h2></div><a class="text-link" href="#">Посмотреть сайт ↗</a></div><div class="admin-banner">Демонстрационный кабинет · Изменения доступны только в этом браузере. Здесь нет авторизации и общей базы. Не вводите реальные данные клиентов.</div><div class="stats"><div class="stat"><strong>${tours.filter(t=>t.active).length}</strong><span>Активных маршрутов</span></div><div class="stat"><strong>${leads.length}</strong><span>Тестовых заявок</span></div><div class="stat"><strong>${leads.filter(l=>l.status==='Новая').length}</strong><span>Ждут ответа</span></div></div><div class="filters"><button class="${adminTab==='tours'?'active':''}" data-tab="tours">Экскурсии</button><button class="${adminTab==='leads'?'active':''}" data-tab="leads">Заявки</button></div><div id="admin-body"></div></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;renderAdmin()});const body=$('#admin-body');if(adminTab==='tours'){body.innerHTML=`<button class="button red" id="add-tour">+ Добавить экскурсию</button>`+tours.map(t=>`<div class="admin-row"><img src="assets/${esc(t.image)}" alt=""><div class="grow"><h3>${esc(t.title)}</h3><p>${esc(t.category)} · ${esc(t.duration)} · ${t.active?'На сайте':'Скрыта'}</p></div><button class="small-button" data-edit="${esc(t.id)}">Редактировать</button><button class="small-button" data-toggle="${esc(t.id)}">${t.active?'Скрыть':'Показать'}</button></div>`).join('');$('#add-tour').onclick=()=>editTour();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editTour(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const next=tours.map(t=>t.id===b.dataset.toggle?{...t,active:!t.active}:t);if(save('cl-tours-v1',next)){tours=next;renderAdmin();renderTours();toast('Видимость обновлена')}})}else{body.innerHTML=leads.length?leads.map(l=>`<div class="admin-row"><div class="grow"><h3>${esc(l.name)}</h3><p>${esc(l.contact)} · ${esc(l.tour)}</p><p>${esc(l.date||'Дата не выбрана')} · ${esc(l.message||'Без комментария')}</p></div><label>Статус<select data-status="${esc(l.id)}">${['Новая','В работе','Согласована','Закрыта'].map(s=>`<option ${l.status===s?'selected':''}>${s}</option>`).join('')}</select></label></div>`).join(''):'<div class="empty">Пока нет заявок.<br>Заполните демоформу на сайте — заявка появится здесь.<br><button class="small-button" id="test-lead" style="margin-top:20px">Создать тестовую заявку</button></div>';if($('#test-lead'))$('#test-lead').onclick=()=>booking();document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{const next=leads.map(l=>l.id===s.dataset.status?{...l,status:s.value}:l);if(save('cl-leads-v1',next)){leads=next;renderAdmin();toast('Статус сохранён')}})}}
function editTour(id){const t=tours.find(t=>t.id===id)||{title:'',description:'',duration:'4 часа',category:'Город',route:'',image:'garden.jpg',tag:'НОВЫЙ МАРШРУТ',active:true};openModal(`<div class="eyebrow accent">РЕДАКТОР ЭКСКУРСИЙ</div><h2>${id?'Редактировать':'Новый маршрут'}</h2><form id="edit" class="form-grid"><label>Название<input required name="title" maxlength="90" value="${esc(t.title)}"></label><label>Описание<textarea required name="description" maxlength="400">${esc(t.description)}</textarea></label><label>Маршрут<textarea required name="route" maxlength="600">${esc(t.route)}</textarea></label><label>Продолжительность<input required name="duration" maxlength="30" value="${esc(t.duration)}"></label><label>Категория<select name="category">${['Город','Вечер','За городом'].map(c=>`<option ${c===t.category?'selected':''}>${c}</option>`).join('')}</select></label><label>Подпись на фото<input name="tag" maxlength="35" value="${esc(t.tag)}"></label><label>Фотография<select name="image">${[['garden.jpg','Сад Юйюань'],['skyline.jpg','Панорама Шанхая'],['canal.jpg','Каналы Чжуцзяцзяо']].map(([v,n])=>`<option value="${v}" ${v===t.image?'selected':''}>${n}</option>`).join('')}</select></label><button class="button red">Сохранить изменения</button></form>`);$('#edit').onsubmit=e=>{e.preventDefault();const value={...t,...Object.fromEntries(new FormData(e.target)),id:id||crypto.randomUUID()};const next=id?tours.map(t=>t.id===id?value:t):[...tours,value];if(!save('cl-tours-v1',next))return;tours=next;renderTours();renderAdmin();$('#modal').close();toast('Экскурсия сохранена')}}
renderTours();route();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'list_tours',description:'List visible Shanghai demo tours.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({tours:tours.filter(t=>t.active)})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'open_tour_details',description:'Open details for a visible tour. Does not create a booking.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:input=>{if(typeof input?.id!=='string'||!tours.some(t=>t.id===input.id&&t.active))throw new Error('Unknown tour');detail(input.id);return{opened:input.id}}})).catch(()=>{})}catch{}}

const menuButton=$('.menu-toggle'),mainNav=$('#main-nav');
function closeMenu(){mainNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Открыть меню')}
menuButton.onclick=()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';mainNav.classList.toggle('open',open);menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню')};
mainNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
$('#country-link').addEventListener('click',()=>document.querySelector('[data-filter="За городом"]').click());
